name: Check Page Availability

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches: [ "main" ]

jobs:
  check-page:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install cURL
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          echo installed cURL
        
      - name: GET and SAVE Id token
        run: |
          # here, will call the POST API to get the token and save it
          echo GET and SAVE token from API
          
      - name: Send Request with id Token
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $PAGE_URL) || RESPONSE=""
          if [ $RESPONSE -eq 200 ]; then
            echo "OTC Page is UP"
          else
            echo "OTC Page is DOWN"
            exit 1
          fi
        env:
          PAGE_URL: "https://hhealthfirst.org/widgets/lofl-otc-widget.html?memberId=138429371&appId=CUSTOMER_CENTER&authorizer=OKTA&lang=en&token="
