name: Check Page Availability

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches: [ "main" ]

jobs:
  check-page:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install cURL
        run: |
          sudo apt-get update && sudo apt-get install -y curl jq
          echo installed cURL
        
      - name: GET and SAVE Id token
        run: |
          RESPONSE=$(curl --request POST \
          --url https://nl9olslot5.execute-api.us-east-1.amazonaws.com/st/api/v1/login \
          --header 'User-Agent: Member-iOS' \
          --header 'X-API-KEY: QqLLrg5CBy70besuoa0Yg8xQ1gpkuHyx5PA6bjeb' \
          --header 'content-type: application/json' \
          --data '{
          "username": "SRUTH",
          "password": "Healthfirst*123"
          }')
          ID_TOKEN=$(echo "$RESPONSE" | jq -r '.data.id_token')
          echo "GET and SAVE token from API ID_TOKEN::$ID_TOKEN"
          
      - name: Send Request with id Token
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $PAGE_URL$ID_TOKEN) || RESPONSE=""
          if [ $RESPONSE -eq 200 ]; then
            echo "OTC Page is UP"
          else
            echo "OTC Page is DOWN"
            exit 1
          fi
        env:
          PAGE_URL: "https://hf-cde-trailblazer-st.healthfirst.org/widgets/lofl-otc-widget.html?memberId=138429371&appId=CUSTOMER_CENTER&authorizer=OKTA&lang=en&token="
